version: '2'
services:
  base-runner:
    image: "${REPO}/base-runner"
    entrypoint: ''
    command: bash

  node-runner:
    image: "${REPO}/node-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
      - ./tsconfig.json:/runner/tsconfig.json

    entrypoint: ''
    user: root
    command: bash

  jvm-runner:
    image: "${REPO}/jvm-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  java-runner:
    image: "${REPO}/java-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
      - ./listen.js:/runner/listen.js
    entrypoint: ''
    command: bash

  ruby-runner:
    image: "${REPO}/ruby-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
      - ./sample_data:/runner/sample_data
    entrypoint: ''
    user: root
    command: bash

  python-runner:
    image: "${REPO}/python-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  func-runner:
    image: "${REPO}/func-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  haskell-runner:
    image: "${REPO}/haskell-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  systems-runner:
    image: "${REPO}/systems-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  erlang-runner:
    image: "${REPO}/erlang-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  alt-runner:
    image: "${REPO}/alt-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  dotnet-runner:
    image: "${REPO}/dotnet-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./templates:/runner/templates
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  dart-runner:
    image: "${REPO}/dart-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  rust-runner:
    image: "${REPO}/rust-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  julia-runner:
    image: "${REPO}/julia-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  crystal-runner:
    image: "${REPO}/crystal-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  swift-runner:
    image: "${REPO}/swift-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  objc-runner:
    image: "${REPO}/objc-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  go-runner:
    image: "${REPO}/go-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  chapel-runner:
    image: "${REPO}/chapel-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  nim-runner:
    image: "${REPO}/nim-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  esolangs-runner:
    image: "${REPO}/esolangs-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  r-runner:
    image: "${REPO}/r-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  # LANGUAGE SPECIFIC HELPERS
  javascript_test:
    image: "${REPO}/node-runner"
    environment:
      - NODE_ENV=test
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/javascript_spec.js'

  coffeescript:
    image: "${REPO}/node-runner"
    environment:
      - NODE_ENV=test
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l coffeescript'

  coffeescript_test:
    image: "${REPO}/node-runner"
    environment:
      - NODE_ENV=test
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/coffeescript_spec.js'

  typescript:
    image: "${REPO}/node-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
      - ./tsconfig.json:/runner/tsconfig.json
    entrypoint: 'node run -l typescript'

  typescript_test:
    image: "${REPO}/node-runner"
    environment:
      - NODE_ENV=test
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 10000 test/runners/typescript_spec.js'

  python:
    image: "${REPO}/python-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l python'

  python_test:
    image: "${REPO}/python-runner"
    environment:
      - NODE_ENV=test
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/python_spec.js'

  python3:
    image: "${REPO}/python-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l python3'

  python3_test:
    image: "${REPO}/python-runner"
    environment:
      - NODE_ENV=test
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/python3_spec.js'

  ruby:
    image: "${REPO}/ruby-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l ruby'

  ruby_test:
    image: "${REPO}/ruby-runner"
    environment:
      - NODE_ENV=test
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/ruby_spec.js'

  sql_test:
    image: "${REPO}/ruby-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/sql_spec.js'

  shell_test:
    image: "${REPO}/ruby-runner"
    environment:
      - NODE_ENV=test
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/shell_spec.js'

  haskell:
    image: "${REPO}/haskell-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l haskell'

  haskell_test:
    image: "${REPO}/haskell-runner"
    environment:
      - NODE_ENV=test
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/haskell_spec.js'

  java:
    image: "${REPO}/jvm-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l java'

  java_test:
    image: "${REPO}/java-runner"
    environment:
      - NODE_ENV=test
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 15000 test/runners/java_spec.js'

  clojure:
    image: "${REPO}/jvm-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l clojure'

  clojure_test:
    image: "${REPO}/jvm-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/clojure_spec.js'

  php:
    image: "${REPO}/alt-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l php'

  php_test:
    image: "${REPO}/alt-runner"
    environment:
      - NODE_ENV=test
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/php_spec.js'

  cpp:
    image: "${REPO}/systems-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l cpp'

  cpp_test:
    image: "${REPO}/systems-runner"
    environment:
      - NODE_ENV=test
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/cpp_spec.js'

  c:
    image: "${REPO}/systems-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l c'

  c_test:
    image: "${REPO}/systems-runner"
    environment:
      - NODE_ENV=test
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/c_spec.js'

  csharp:
    image: "${REPO}/dotnet-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./templates:/runner/templates
      - ./test:/runner/test
    entrypoint: 'node run -l csharp'

  csharp_test:
    image: "${REPO}/dotnet-runner"
    environment:
      - NODE_ENV=test
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./templates:/runner/templates
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/csharp_spec.js'

  fsharp:
    image: "${REPO}/dotnet-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l fsharp'

  fsharp_test:
    image: "${REPO}/dotnet-runner"
    environment:
      - NODE_ENV=test
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 7000 test/runners/fsharp_spec.js'

  elixir:
    image: "${REPO}/erlang-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l elixir'

  elixir_test:
    image: "${REPO}/erlang-runner"
    environment:
      - NODE_ENV=test
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/elixir_spec.js'

  erlang:
    image: "${REPO}/erlang-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l erlang'

  erlang_test:
    image: "${REPO}/erlang-runner"
    environment:
      - NODE_ENV=test
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/erlang_spec.js'

  rust_test:
    image: "${REPO}/rust-runner"
    environment:
      - NODE_ENV=test
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/rust_spec.js'

  dart_test:
    image: "${REPO}/dart-runner"
    environment:
      - NODE_ENV=test
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/dart_spec.js'

  kotlin:
    image: "${REPO}/jvm-runner"
    environment:
      - NODE_ENV=test
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l kotlin'

  kotlin_test:
    image: "${REPO}/jvm-runner"
    environment:
      - NODE_ENV=test
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/kotlin_spec.js'

  crystal:
    image: "${REPO}/crystal-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l crystal'

  crystal_test:
    image: "${REPO}/crystal-runner"
    environment:
      - NODE_ENV=test
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/crystal_spec.js'

  ocaml-runner:
    image: "${REPO}/ocaml-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l ocaml'

  ocaml_test:
    image: "${REPO}/ocaml-runner"
    environment:
      - NODE_ENV=test
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'bash /home/"${REPO}er/run_ocaml.sh mocha -t 5000 test/runners/ocaml_spec.js'

  swift:
    image: "${REPO}/swift-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l swift'

  swift_test:
    image: "${REPO}/swift-runner"
    environment:
      - NODE_ENV=test
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/swift_spec.js'

  objc:
    image: "${REPO}/objc-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks/objc/objc:/usr/include/GNUstep/objc
      - ./frameworks/objc/CW:/usr/include/GNUstep/CW
    entrypoint: 'node run -l obcj'

  objc_test:
    image: "${REPO}/objc-runner"
    environment:
      - NODE_ENV=test
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks/objc/objc:/usr/include/GNUstep/objc
      - ./frameworks/objc/CW:/usr/include/GNUstep/CW
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/objc_spec.js'

  go:
    image: "${REPO}/go-runner"
    volumes:
      - ./lib:/runner/lib
      - ./frameworks:/runner/frameworks
    entrypoint: 'node run -l go'

  go_test:
    image: "${REPO}/go-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    entrypoint: 'mocha -t 5000 test/runners/go_spec.js'

  nim:
    image: "${REPO}/nim-runner"
    volumes:
      - ./lib:/runner/lib
      - ./frameworks:/runner/frameworks
    entrypoint: 'node run -l nim'

  nim_test:
    image: "${REPO}/nim-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/nim_spec.js'

  r:
    image: "${REPO}/r-runner"
    volumes:
      - ./lib:/runner/lib
      - ./frameworks:/runner/frameworks
    entrypoint: 'node run -l r'

  r_test:
    image: "${REPO}/r-runner"
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/r_spec.js'
